responseApp/AppBase/urls.py
from django.urls import path
from django.conf.urls.static import static
from responseApp import settings
from . import views
name_app = 'baseApp'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('tovar/<int:pk>',views.TovarDetail.as_view(),name = 'tovar'),
    path('tovar_create/',views.CreateTovarCreateView.as_view(),name = 'tovar_create'),
    path('tags/<int:pk>', views.GetTags.as_view(), name='get_tags'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

responseApp/register/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'register'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='AppBase/home.html'), name='logout'),
    path('create_profile/', views.CreateUser.as_view(), name='create_profile'),
    path('profile/', views.Profile.as_view(), name='view_profile'),
    path('edit_profile/', views.EditProfile.as_view(), name='edit_profile'),

]

responseApp/responseApp/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppBase.urls'), name='home'),
    path('users/',include('register.urls',namespace='register')),
    path('__debug__/',include(debug_toolbar_urls())),
    path("__reload__/", include("django_browser_reload.urls")),
]


admin.site.site_header = 'Отзовик'
admin.site.index_title = 'Модели'

responseApp/register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image



class User(AbstractUser):
    photo = models.ImageField(upload_to='avatar',blank=True,null=True, verbose_name='Фото пользователя')

responseApp/register/forms.py
from typing import Any
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
class UserLoginForm(AuthenticationForm):

    class Meta:

        base:str = " bg-panel border-b-4 border-dark_panel",


        model = get_user_model()
        fields = ('username', 'password')
        widgets = {
            'username': forms.TextInput(attrs={
                'class': f" row-start-2 col-start-1 {base}",
                'placeholder':'Имя',
                'autocomplete':'off'}),
            'password': forms.PasswordInput(attrs={
                'class': f" row-start-4  {base}",
                'placeholder':'Пароль',
                'autocomplete':'off'}),
            
        }
    

        

class CreateUserForm(UserCreationForm):

    style = {
            'base': "h-[40px] transition-colors focus:border-dark_panel border-0 focus:border-b-4 focus:outline-none focus:ring-0 bg-panel border-b-4 border-dark_panel/50   w-full",

            }
    username = forms.CharField(label='Логин',widget=forms.TextInput(attrs={'class':' transition-colors focus:border-dark_panel border-0 focus:border-b-4 focus:outline-none focus:ring-0 bg-panel border-b-4 border-dark_panel/50  px-2 py-1 w-full','placeholder':"Имя пользователя"}))
    password1 = forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class':f' {style.get("base")} ','placeholder':"Пароль"}))
    password2 = forms.CharField(label='Повторите пароль',widget=forms.PasswordInput(attrs={'class':f'  {style.get("base")}','placeholder':"Повторите пароль"}))
        
    class Meta:
        model = get_user_model()
        fields = ['username','email','photo','password1','password2']

        widgets = {'email':forms.EmailInput(attrs={
            'class':'  transition-colors focus:border-dark_panel border-0 focus:border-b-4 focus:outline-none focus:ring-0 bg-panel border-b-4 border-dark_panel/50  px-2 py-1 w-full row-start-3','placeholder':"Почта"
        })}

        order = ['username','email','password1','password2']
        
class EditUserForm(forms.ModelForm):
    
    class Meta:
        
        base= "h-[40px] transition-colors focus:border-dark_panel border-0 focus:border-b-4 focus:outline-none focus:ring-0 bg-panel border-b-4 border-dark_panel/50   w-full",

            
        model = get_user_model()
        fields = ['username','photo','first_name','last_name']
        
        widgets = {
            'username':forms.TextInput(attrs={'class':f' col-start-2 row-start-2 {base}','placeholder':"Имя пользователя"}),
            'first_name':forms.TextInput(attrs={'class':f'col-start-2 row-start-4 {base}','placeholder':"Имя"}),
            'last_name':forms.TextInput(attrs={'class':f' col-start-2 row-start-6 {base}','placeholder':"Фамилия"}),
            'photo':forms.FileInput(attrs={'class':' hidden','placeholder':"Фото"}),
            
        }

responseApp/register/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render ,redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView,DetailView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .forms import UserLoginForm, CreateUserForm,EditUserForm


# Create your views here.

class UserLogin(LoginView):
    next_page = reverse_lazy('home')
    form_class = UserLoginForm
    redirect_authenticated_user = True
    template_name = 'register/login.html'
    # def get_success_url(self) -> str:
    #     return reverse_lazy('home')
    
    

    
class CreateUser(CreateView):
    form_class = CreateUserForm
    template_name = 'register/register.html'
    
    def get_success_url(self) -> str:
        
        print(self.request.GET)

    


class Profile(LoginRequiredMixin,DetailView):
    template_name = 'register/profile.html'
    
    def get_object(self, queryset = None):
        return self.request.user
    

    
class EditProfile(UpdateView):
    template_name = 'register/editable_profile.html'
    form_class = EditUserForm
    success_url = reverse_lazy('register:view_profile')
    

    def get_object(self, queryset = None):
        return self.request.user
    
        

responseApp/templates/register/editable_profile.html
{% extends "base.html" %}
{% load static %}


{% block tovarName %}
    {{ block.super }} &gt Редактирование профиля
{% endblock tovarName %}


{% block content %}
<main class='w-full h-screen flex justify-center items-center'>
    <form action="" method='post' enctype='multipart/form-data'>
        {% csrf_token %}

    <div class='shadow-inner shadow-[#65558F]/70 p-3 w-[600px] bg-panel h-max rounded-xl'>

        <div class='grid grid-cols-[150px,200px,1fr] grid-rows-[20px,30px,10px,30px,10px,30px,10px,30px,1fr]'>
            

            
            {% if user.photo %}
            <img src="{{user.photo.url}}" width='150' class='rounded-xl col-span-2 col-start-1 row-start-1'alt="Avatar"> 
            {% else %}
            <img src="{% static 'img/noimage.jpg' %}" width='150'  class='rounded-xl col-span-2 col-start-1 row-start-1'alt="Avatar"> 
            {% endif %}
                
            <label for="{{form.photo.id_for_label }}" class='mt-2 col-start-1 row-start-8 flex justify-center content-center'>
                <p class=' cursor-pointer hover:rounded-md  transition-all hover:bg-dark_panel/30 text-dark_panel font-bold'>Изменить фото</p>
            {{form.photo}}
        </label>
           {% for f in  form%}
            
            {% if f == form.photo %}
            {% else %}
            {{f}}
            {% endif %}
                
           {% endfor %}
            <button type="submit" class='bg-button col-start-3 row-start-2 ml-4 row-span-4 active:bg-panel mt-10  transition-colors h-12 p-2 w-max  rounded-[100px]  shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]  gap-2 text-[#65558f] font-bold'>Подтвердить изменения</button>
        </div>


    </div>
</form>
</main>
{% endblock content %}
    
    

responseApp/templates/register/login.html
{% extends 'base.html' %}
{% load static %}

{% block headOther %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Baskervville+SC&display=swap" rel="stylesheet">
{% endblock headOther %}

{% block tovarName %}
    {{ block.super }} &gt Вход
{% endblock tovarName %}


{% block title %}
    Вход в аккаунт
{% endblock title %}
    


{% block content %}
    <main class='h-[100vh] grid grid-cols-3 grid-rows-3'>
        
        <div class='grid grid-cols-3 rounded-3xl shadow-inner shadow-[#65558F]/40 col-start-2 row-start-2 bg-panel '>
             <img src="{% static 'svg/login.svg' %}" width="200px" class='col-start-1 mt-[60px]' alt="">
                <form autocomplete="off" class=' active:outline-none row-start-1 col-start-2 grid grid-rows-[1fr,24px,30px,24px,40px,48px,1fr] 'action="" method='post'>
                    {% csrf_token %}
                    <input type="text" name="{{form.username.name}}" placeholder="Имя" class='transition-colors focus:border-dark_panel border-0 focus:border-b-4 focus:outline-none focus:ring-0 bg-panel border-b-4 border-dark_panel/50 row-start-2 col-start-1'>
                    <input type="text" name="{{form.password.name}}" placeholder="Пароль" class='transition-colors focus:border-dark_panel border-0 focus:border-b-4 focus:outline-none focus:ring-0 bg-panel border-b-4 border-dark_panel/50 row-start-4 col-start-1'>
                        <button type="submit" class='bg-button active:bg-panel col-start-1 row-start-6 transition-colors h-12 p-2 w-[200px]  rounded-[100px]  shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]  gap-2 text-[#65558f] font-bold'>Войти</button>
                        <a href="{% url 'register:create_profile' %}" class='font-Baskervville row-start-7 text-center mt-3 text-[#757575]'>Нету аккаунта? Зарегистрируйтесь</a>
                </form>

        </div>
    </main>
{% endblock content %}
    


    

responseApp/templates/register/profile.html
{% extends 'base.html' %}
{% load static %}


{% block tovarName %}
    {{ block.super }} &gt Профиль
{% endblock tovarName %}



{% block content %}
    <main class='w-full h-screen flex justify-center items-center'>
        

            



            
        <div class='shadow-inner shadow-[#65558F]/70 p-3 w-[600px] bg-panel h-max rounded-xl'>

            <div class='grid grid-cols-[130px,20px,1fr] grid-rows-[20px,30px,10px,30px,10px,30px,10px,30px,1fr]'>
                <div class='flex justify-end'>
                    <a href="{% url 'register:edit_profile' %}" title='Редактировать профиль'>
                        <img src="{% static 'svg/edit.svg' %}" class='bg-dark_panel/30 rounded-xl p-1'width='34' alt="edit icon"> 
                    </a>
                </div>
                {% if object.photo %}
                <img src="{{object.photo.url}}" class='rounded-xl col-span-2 col-start-1 row-start-1'  alt="Фото пользователя">
                {% else %}
                <img src="{% static 'img/noimage.jpg' %}"  class=' rounded-md col-span-2 col-start-1 row-start-1' alt="Фото пользователя">
            {% endif %}
            {% if object.is_active %}
                <div class=' col-start-2 row-start-1 w-5 h-5 bg-green-500 rounded-full'></div>
                {% else %}
                <div class=' col-start-2 row-start-1 w-5 h-5 bg-red-500 rounded-full'></div>
            {% endif %}
                
                <p class='col-start-3 row-start-2 font-bold text-dark_panel ml-4'>
                    Никнейм: {{ object.username }}
                </p>
                <p class='col-start-3 row-start-4 font-bold text-dark_panel ml-4 '>
                    Имя: {% if  object.first_name %}
                    {{ object.first_name }}
                    {% else %}
                    Не указано
                    {% endif %}
                </p>
                <p class='col-start-3 row-start-6 font-bold text-dark_panel ml-4'>
                    Фамилия: {% if object.last_name %}
                    {{object.last_name}}
                    {% else %}
                    Не указано
                    {% endif %}
                </p>
            </div>


        </div>
    </main>
{% endblock content %}
    

responseApp/templates/register/register.html
{% extends 'base.html' %}
{% load static %}


    
{% block content %}
    <main class='h-[100vh] grid grid-cols-3 grid-rows-3'>
        <div class='grid grid-cols-[1fr,207px,1fr] rounded-3xl shadow-inner shadow-[#65558F]/40 col-start-2 h-[500px] row-start-2 bg-panel '>
            <img width='700px' class='opacity-5 shadow-inner translate-x-[-60px] translate-y-[-90px]   fixed col-start-1'src="{% static 'svg/register.svg' %}" alt="">
            <form enctype='multipart/form-data' autocomplete="off" class='z-10  row-start-1 col-start-2 'action="" method='post'>

                {% csrf_token %}
                <div class='w-full h-full 3'>
                    {% for f in form %}
                        <div class="mt-10">
                            {{ f }}
                            
                        </div>
                            {% if f.errors %}
                            {% for er in f.errors %}
                            <div class='translate-x-[26rem] translate-y-[-60px] fixed '>
                                <div class='bg-dark_panel translate-y-3  rounded-md w-3 h-3'></div>
                                <p class='bg-panel  rounded-md w-[300px] shadow-inner shadow-[#65558F]/40 p-1 text-center'>{{er}}</p>
                            </div> 
                            {% endfor %}
                                
                            {% endif %}
                    {% endfor %}
                    <div class="grid grid-cols-1 row-start-6"> 
                        <button type="submit" class='bg-button active:bg-panel mt-10  transition-colors h-12 p-2 w-[200px]  rounded-[100px]  shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]  gap-2 text-[#65558f] font-bold'>Регистрация</button>
                    </div>
                    <div class="grid grid-cols-1 row-start-7">
                        <a href="{% url 'register:login' %}" class='font-Baskervville text-center mt-3 mr-4 text-[#757575]'>Войти</a>
                    </div>
                </div>
            </form>
                
        </div>
    </main>
{% endblock content %}