responseApp/AppBase/urls.py
from django.urls import path
from django.conf.urls.static import static
from responseApp import settings
from . import views
name_app = 'baseApp'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('tovar/<int:pk>',views.TovarDetail.as_view(),name = 'tovar'),
    path('tovar_create/',views.CreateTovarCreateView.as_view(),name = 'tovar_create'),
    path('tags/<int:pk>', views.GetTags.as_view(), name='get_tags'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

responseApp/register/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'register'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='AppBase/home.html'), name='logout'),
    path('create_profile/', views.CreateUser.as_view(), name='create_profile'),
    path('profile/', views.Profile.as_view(), name='view_profile'),
    path('edit_profile/', views.EditProfile.as_view(), name='edit_profile'),

]

responseApp/responseApp/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppBase.urls'), name='home'),
    path('users/',include('register.urls',namespace='register')),
    path('__debug__/',include(debug_toolbar_urls())),
    path("__reload__/", include("django_browser_reload.urls")),
]


admin.site.site_header = 'Отзовик'
admin.site.index_title = 'Модели'

responseApp/templates/base.html
{% comment %} 
    content - Основной контект 
    cssLinks - Теги link для css
    title - блок тайтла
    user - Данные о юзере
{% endcomment %}

<!DOCTYPE html>
{% load static tailwind_tags%}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
    Домашняя страница
    {% endblock title %}
      </title>

      {% tailwind_css %}


    {% block headOther %}
      
    {% endblock headOther %}
      <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body class='scroll-smooth'>
    <header class='fixed top-2 z-10 w-full ' >
      <div class='max-h-[64px] grid grid-rows-[8px,1fr,1fr] grid-cols-[30px,50px,400px,1fr,400px] w-[95%] mr-20 h-[64px] ml-12  bg-panel rounded-2xl shadow-inner shadow-[#65558F]/20 '>

        <div class='row-start-2 col-start-4 grid  justify-center justify-items-center max-h-16 h-[45px]'>
            <span class='row-start-2 col-start-2 text-dark_panel font-bold'><p>{% block tovarName %}<a href='{% url "home" %}'>Отзовик</a>{% endblock tovarName %}</p></span>
        </div>
        <div class='col-start-2 row-start-2 h-12 w-12 '>
            <img class='menuBtn w-12 h-12' src="{% static 'svg/menu.svg' %}" alt="menu">
            <div class=' menu transition-all hidden bg-panel w-[200px]  flex justify-center rounded-xl translate-x-[-30px] h-60 translate-y-5 border-b-4 border-dark_panel border-solid shadow-inner shadow-[#65558F]/50'>
                
                <ul class='flex flex-col'>
                    {% for item in mainmenu %}
                   


                    <li class=' mt-10 text-dark_panel   font-bold h-[30px] hover:scale-[1.2] transition-all cursor-pointer hover:rounded-md hover:bg-dark_panel/15 grid grid-cols-[24px,1fr] grid-rows-1'> <img src="{% static item.ico %}" class='col-start-1' alt=""><a href="
                        {% if item.urlLink %}
                            {% url item.urlLink %}
                        {% endif %}
                            ">{{item.title}}</a></li>

                    {% endfor %}
                        
                    
                        
                </ul>
                    
            </div>
        </div>
            <div class="w-96 col-start-5 row-start-1 grid grid-cols-3 grid-rows-[8px,1fr,8px] max-h-[64px]">
                <button type="button" class='bg-button active:bg-panel col-start-1 row-start-2 transition-colors h-12 p-2 w-[200px] max-sm:col-start-4   rounded-[100px]  shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]  gap-2 text-[#65558f] font-bold'>
                    <a href="{% url 'tovar_create' %}">+ Добавить товар</a>
                </button>
                {% with request.user as user %}
                <div class='flex items-center justify-center col-start-3 row-start-2 translate-x-[-15px]  h-12 bg-button rounded-3xl w-max active:bg-panel text-dark_panel font-bold p-2 cursor-pointer shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]'>
                    {% if user.is_authenticated %}
                        <p class='mr-2 logout'>Выйти |</p><a href="{% url 'register:view_profile' %}">{{user.username}}</a>
                    {% else %}
                        <a href="{% url 'register:login' %}">Войти</a>
                    {% endif %}
                {% endwith %}
                </div> 
            </div>
        </div>
    </header>
    <div  class='modalWindow  hidden grid-cols-[700px,1fr,700px] grid-rows-3  p-3  bg-black/60 fixed top-0 z-10 w-full h-full'>
        <form class = 'grid grid-cols-[25px,1fr,1fr,1fr,1fr,25px] row-start-2 rounded-md col-start-2 bg-panel w-[255px] h-[310px] grid-rows-[30px,50px,100px,1fr,3rem] m-0 p-3'action="{% url 'register:logout' %}" method="post">
            <img class='col-start-3 row-start-3 col-span-3'width='100'src="{% static 'svg/logout.svg' %}" alt="logout ico">
            <p class='mt-1 text-center col-start-1 row-start-1 col-span-6 text-dark_panel font-bold'>Вы уверены что хотите выйти?</p>
            {% csrf_token %}
            <button class='no bg-button hover:bg-[#fad7d7] active:bg-panel col-start-1 col-span-3 row-start-4 transition-colors h-12 p-2 w-[100px] max-sm:col-start-4   rounded-[100px]  shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]  gap-2 text-[#65558f] font-bold' type="button">Нет</button>
            <button class='bg-button hover:bg-[#d9fad7] active:bg-panel col-start-5 col-span-3 row-start-4 transition-colors h-12 p-2 w-[100px]    rounded-[100px]  shadow-[0_-0px_10px_-3px_rgba(0,0,0,0.5)]  gap-2 text-[#65558f] font-bold'type="submit">Да</button>
        </form>
    </div>

        
        {% block content %}
        
        {% endblock content %}
            

<script src='{% static "js/index.js" %}'></script>
</body>
</html>